server:
  port: 7081

spring:
  application:
    name: demo
  profiles:
    active: development

  datasource:
    url: jdbc:postgresql://localhost:54321/postgres?currentSchema=demo
    username: postgres
    password: postgres

  jpa:
    open-in-view: false

springdoc:
  api-docs:
    enabled: true
    path: /demo/v3/api-docs
  swagger-ui:
    enabled: true
    path: /demo/swagger-ui.html
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha

rsa:
  public-key: classpath:certs/public.pem

my-env: ${MY_ENV:default}
