--liquibase formatted sql

--changeset metin.durmaz:01
CREATE TABLE order_ms.orders
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    address VARCHAR(255)                            NOT NULL,
    price   DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);
