--liquibase formatted sql

--changeset metin.durmaz:01
CREATE TABLE order_ms.orders
(
    price   double precision,
    id      bigint GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    address varchar(255),
    name    varchar(255)
);
CREATE SEQUENCE IF NOT EXISTS orders_id_seq start 1000 increment 1;

