pipeline {
    agent { label 'agent-1' }

    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout scmGit(branches: [[name: "$BRANCH_NAME"]], extensions: [], userRemoteConfigs: [[url: 'https://github.com/metin-durmaz/jenkins-poc.git']])
            }
        }
        stage('Maven Package') {
            steps {
                sh '''
                    mvn clean package -DskipTests -U
                    cd target/
                    mv demo.jar demo-${BUILD_NUMBER}.jar
                '''
            }
        }
        stage('Test') {
            steps {
                sh "mvn test"
            }

            post {
                always {
                    junit testResults: 'target/surefire-reports/*.xml', skipPublishingChecks: true
                }
            }
        }
    }
}
